### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by runette** [sergiois/cfgist#1]
I take it no one has ever used this but you - since it is hard coded to go to your personal GH repo only

**Comment by sergiois** [comment]
Hello @runette ! I review it as soon as possible.

**Comment by runette** [comment]
I got it working. - see https://www.runette.co.uk/post/4-os-openspace-maps-in-openlayers-6

The problem is in this file https://github.com/sergiois/cfgist/blob/master/tmpl/cfgist.php on line 20

I deleted `sergiois/` from the file. I then put `runette/` followed by the gist id into the default value of the custom field

**Comment by sergiois** [comment]
Fixed problem! Thanks @runette 
New version: https://github.com/sergiois/cfgist/releases/tag/v1.0.2
